HttpException: don't inherit from ConnectionException.
The latter is meant for issuse with connecting, so HttpException shouldn't inherit
from it. It confuses error handling and already introduced a bug in EteSync on
Android.